spring:
  application:
    name: paper-ai-agent
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:54333/paper_helper # 你的pgvector向量数据库
    username: pgvector
    password: pgvector
  ai:
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json
    dashscope:
      api-key: your-api-key
      observations:
        log-completion: true
        log-prompt: true
      chat:
        options:
          model: qwen-plus
      embedding:
        options:
          model: text-embedding-v4
          dimensions: 1024
    chat:
      client:
        observations:
          # default value is false.
          log-prompt: true
          log-completion: true
          include-error-logging: true
    vectorstore: # 本项目没有使用配置文件辅助自动装配pgvector，而是手动配置
      pgvector:
        index-type: HNSW
        dimensions: 1024
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  tools:
    observability:
      # default value is false.
      include-content: true
  http:
    client:
      read-timeout: 60s

search-api:
  api-key: your-api-key

server:
  port: 8123
  servlet:
    context-path: /api


# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.example.paperaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


services:
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
